### ISSUE TITLE
How to use multiple primary keys as query conditions?

### ISSUE THREAD

**Issue by pili2026** [Metaswitch/cassandra-sys-rs#22]
Hi, it’s me again.

The question I want to ask this time is, if there is a table that needs to use multiple primary keys as conditions to query, is the index field of `cass_statement_bind_string` changed? or add a new `cass_statement_bind_string`?

However, I have tried the following ways:
```rust
     let query_check = "SELECT * FROM test_ks.t_sta_mgnt_date WHERE deviceid = primary_key and epoch = primary_key_2"
      let statement = cass_statement_new(CString::new(query_check).unwrap().as_ptr(), 0);
      cass_statement_bind_string(statement, 0, CString::new(primary_key).unwrap().as_ptr());
      cass_statement_bind_string(statement, 1, CString::new(primary_key_2).unwrap().as_ptr());
```
But, the query cannot be made. Is it related to the setting of the parameters?

**Comment by kw217** [comment]
Hi @pili2026 - I suggest you read the DataStax documentation, especially https://docs.datastax.com/en/developer/cpp-driver/2.11/topics/basics/binding_parameters/ . This explains how you should bind parameters for queries like the one you suggest. In your example you have no `?` so there are no variables to bind.
