### ISSUE TITLE
ubuntu 18.04

### ISSUE THREAD

**Issue by rukai** [Metaswitch/cassandra-sys-rs#49]
The latest ubuntu that datastax provides images for is ubuntu 18.04.
github actions is about to deprecate ubuntu 18.04 with brown outs starting this month: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
This project relies on those 18.04 package for its CI.

What should the response of this project be?
The possible options I can think of:
* move cassandra-sys to vendoring the dependency by fetching the source and building it? (maybe only behind a cargo feature but use that cargo feature on CI?)
* come up with our own ubuntu packages and publish them somewhere?
* Just script the building of the cpp driver from within ci?

I know the driver can be built just fine on a modern linux system because it builds successfully on my local arch linux machine.

**Comment by kw217** [comment]
Interesting. Thanks for flagging this.

I don't think we can take on building our own packages; that's tantamount to forking the Datastax driver, and in any case it must be a problem for folks writing in C/C++, not just Rust.

In the short term we can probably just update our build to use Ubuntu 20.04, but with the 18.04 drivers (and if that doesn't work, just script the build within our own CI). But the fact they're not being updated means there's a bigger concern here.

Do you know what others in the Cassandra community are doing about the lack of up-to-date drivers?

**Comment by rukai** [comment]
> In the short term we can probably just update our build to use Ubuntu 20.04, but with the 18.04 drivers (and if that doesn't work, just script the build within our own CI). But the fact they're not being updated means there's a bigger concern here.

I did try that, force install the 18.04 packages on ubuntu 20.04, but that results in linker errors when building cassandra-rs.

For my own project I ended up just writing a script to generate and install a package built for the local ubuntu.
This can be used both locally and on CI.
Feel free to copy it from here https://github.com/shotover/shotover-proxy/pull/839

**Comment by kw217** [comment]
Thanks! Logistically I need a DCO, so if you could put that script into a PR against this repo I would be very grateful. This probably is the simplest approach for now. Presumably we'll need to do it for cassandra-rs as well.
